TRI_LAYER_ENABLE = yes

OLED_ENABLE = no
ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no
EXTRAKEY_ENABLE = yes
WPM_ENABLE = no
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes        # Mouse keys
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
LTO_ENABLE = yes
SPLIT_KEYBOARD = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes
SERIAL_USART_HALF_DUPLEX = yes  # Likely needed for single wire
CAPS_WORD_ENABLE = yes
